---
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: detect-startup-automated-script
  namespace: argocd
spec:
  tags: ["MITRE", "T1059"] 
  message: "New Startup Automated Script detected -- possibly the adversary is trying to run malicious code"
  file:
    severity: 5
    matchDirectories:
    - dir: /etc/rc0.d/
    - dir: /etc/rc1.d/
    - dir: /etc/rc2.d/
    - dir: /etc/rcS.d/
    action: Audit