---
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: detect-c2-communication
  namespace: sr-connect-sync
spec:
  network:
    matchProtocols:
    - protocol: TCP
  process:
    matchPaths:
    - path: /bin/nc
  action: Audit
  severity: 5
  message: "Potential C2 communication detected"
