---
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: detect-exec-in-tmp
  namespace: argocd
spec:
  tags:
  - CIS
  - CIS-control-1.1.5
  severity: 4
  message: Alert! Execution attempted inside tmp folder
  process:
    matchDirectories:
    - dir: /tmp/
      recursive: true
  action: Audit
