---
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: detect-chmod-and-chown
  namespace: argocd
spec:
  message: "Detect chmod and chown"
  tags : ["MITRE", "T1222.002"]
  process:
    matchPatterns:
    - pattern: /**/chmod
    - pattern: /**/chown
    severity: 2 
    action: Audit
