---
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: detect-c2-communication
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: argo-cd
  network:
    matchProtocols:
    - protocol: TCP
  process:
    matchPaths:
    - path: /bin/nc
  action: Audit
  severity: 5
  message: "Potential C2 communication detected"

---
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: detect-c2-communication
  namespace: bsp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bsp
  network:
    matchProtocols:
    - protocol: TCP
  process:
    matchPaths:
    - path: /bin/nc
  action: Audit
  severity: 5
  message: "Potential C2 communication detected"

---
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: detect-c2-communication
  namespace: rest-api-dev
spec:
  network:
    matchProtocols:
    - protocol: TCP
  process:
    matchPaths:
    - path: /bin/nc
  action: Audit
  severity: 5
  message: "Potential C2 communication detected"

---
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: detect-c2-communication
  namespace: kyverno
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kyverno
  network:
    matchProtocols:
    - protocol: TCP
  process:
    matchPaths:
    - path: /bin/nc
  action: Audit
  severity: 5
  message: "Potential C2 communication detected"