apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubearmor-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://nexus.adaptavist.com/repository/platform-eng-helm'
    chart: raw-chart
    targetRevision: v0.1.0
    helm:
      valuesObject:
        templates:
          - |
            apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-egress-all
              namespace: kubearmor
            spec:
              policyTypes:
              - Egress
              podSelector: {} 
              egress:
              - to: []
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubearmor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
