apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubearmor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kubearmor.github.io/charts'
    targetRevision: 1.3.2
    chart: kubearmor
    helm:
      values: |
        environment:
          name: EKS
  destination:
    server: https://kubernetes.default.svc
    namespace: kubearmor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
