apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: block-c2-communication
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/bin/nc"
      matchActions:
      - action: "Sigkill"
    message: "Network connection attempt by other than /bin/nc"
