apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: block-exec-in-tmp
spec:
  kprobes:
  - call: "security_bprm_check"
    syscall: false
    args:
    - index: 0
      type: "linux_binprm"
    returnArg:
      index: 0
      type: "int"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/tmp/"
      matchActions:
      - action: "Sigkill" 