apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "deny-write-to-system-path"
spec:
  kprobes:
  - call: "security_file_permission"
    message: "Someone is trying to write to system binary/configuration path !!!"
    syscall: false
    return: true
    args:
    - index: 0
      type: "file" # (struct file *) used for getting the path
    - index: 1
      type: "int"  # 0x04 is MAY_READ, 0x02 is MAY_WRITE
    returnArg:
      index: 0
      type: "int"
    returnArgAction: "Post"
    selectors:
    - matchArgs:      
      - index: 0
        operator: "Prefix"
        values:
        - "/bin"
        - "/usr/bin"
        - "/sbin"
        - "/usr/sbin"
        - "/usr/lib"
        - "/boot"
      - index: 1
        operator: "Equal"
        values:
        - "2"
      matchActions:
      - action: Sigkill