apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-exec-in-tmp
spec:
  tags:
  - CIS
  - CIS-control-1.1.5
  message: Alert! Execution attempted inside tmp folder
  selector:
    matchLabels:
      run: busybox
  process:
    matchDirectories:
    - dir: /tmp/
      recursive: true
  action: Block
